"""
Booking model for turf management system.
Stores booking information in Supabase PostgreSQL.
"""
from __future__ import annotations

import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone


class Booking(models.Model):
    """
    Booking model representing a ground slot reservation.
    
    Schema matches the specified Supabase table:
    - Unique_ID: Primary key (VARCHAR 50)
    - Booking_ID: Auto-increment serial
    - User_ID: Foreign key to User
    - Ground_ID: Foreign key to Ground (stored as INT)
    - Slot_ID: Foreign key to Slot (stored as INT)
    - Date: Booking date
    - Metadata: JSONB field for additional data
    - Status: Booking status (Done, Rejected, Waitlist Processing)
    - Created_At: Timestamp of creation
    """
    
    # Status choices
    STATUS_DONE = "Done"
    STATUS_REJECTED = "Rejected"
    STATUS_WAITLIST = "Waitlist Processing"
    
    STATUS_CHOICES = [
        (STATUS_DONE, "Done"),
        (STATUS_REJECTED, "Rejected"),
        (STATUS_WAITLIST, "Waitlist Processing"),
    ]
    
    # Primary key - unique booking identifier
    unique_id = models.CharField(
        max_length=50,
        primary_key=True,
        editable=False,
        db_column="Unique_ID",
    )
    
    # Note: Booking_ID will be auto-generated by database as SERIAL
    # We don't define it in the model since Django doesn't support
    # non-primary-key AutoField. The database handles it via SERIAL type.
    
    # Foreign key to User
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.RESTRICT,  # Prevent deletion of users with bookings
        db_column="User_ID",
        related_name="bookings",
    )
    
    # Ground ID (references Ground table - not creating FK to avoid dependency)
    ground_id = models.IntegerField(
        db_column="Ground_ID",
    )
    
    # Slot ID (references Slot table - not creating FK to avoid dependency)
    slot_id = models.IntegerField(
        db_column="Slot_ID",
    )
    
    # Booking date
    date = models.DateField(
        db_column="Date",
    )
    
    # Metadata stored as JSON
    metadata = models.JSONField(
        default=dict,
        blank=True,
        db_column="Metadata",
    )
    
    # Booking status
    status = models.CharField(
        max_length=30,
        choices=STATUS_CHOICES,
        default=STATUS_WAITLIST,
        db_column="Status",
    )
    
    # Creation timestamp
    created_at = models.DateTimeField(
        default=timezone.now,
        db_column="Created_At",
    )
    
    class Meta:
        db_table = "Booking"  # Match the exact table name in Supabase
        ordering = ["-created_at"]
        verbose_name = "Booking"
        verbose_name_plural = "Bookings"
        
        # Composite index for efficient queries
        indexes = [
            models.Index(fields=["user", "date"]),
            models.Index(fields=["ground_id", "date", "slot_id"]),
            models.Index(fields=["status"]),
        ]
        
        # Ensure unique booking per slot per date
        constraints = [
            models.UniqueConstraint(
                fields=["ground_id", "slot_id", "date"],
                condition=models.Q(status="Done"),
                name="unique_active_booking_per_slot",
            )
        ]
    
    def save(self, *args, **kwargs):
        """Override save to generate unique_id if not set."""
        if not self.unique_id:
            # Generate unique booking ID in format: BK<YYYYMMDD><random>
            date_str = timezone.now().strftime("%Y%m%d")
            random_suffix = uuid.uuid4().hex[:6].upper()
            self.unique_id = f"BK{date_str}{random_suffix}"
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f"{self.unique_id} - {self.user.email} - {self.date}"
    
    @property
    def is_active(self) -> bool:
        """Check if booking is active (Done status)."""
        return self.status == self.STATUS_DONE
    
    @property
    def can_be_cancelled(self) -> bool:
        """Check if booking can be cancelled (before slot time)."""
        from datetime import datetime, timedelta
        
        # Only Done bookings can be cancelled
        if self.status != self.STATUS_DONE:
            return False
        
        # Check if current time is before the booking date
        # In production, you'd check against slot start time
        now = timezone.now().date()
        return self.date > now
