# Generated by Django 5.0.6 on 2025-11-23 14:08

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ends_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Event end date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(default='admin', help_text='Name of the organizer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Tournament description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_text',
            field=models.CharField(help_text='Venue location', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_contact',
            field=models.CharField(help_text='Contact number of organizer', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster_id',
            field=models.CharField(help_text='Poster filename or URL selected by user', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='sport_id',
            field=models.IntegerField(help_text='Sport ID reference'),
        ),
        migrations.AlterField(
            model_name='event',
            name='starts_at',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='published', max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Tournament/Event title', max_length=120),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at', 'status'], name='events_even_starts__05a37c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['ends_at'], name='events_even_ends_at_4aabb3_idx'),
        ),
    ]
