# Generated by Django 5.0.6 on 2025-11-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='team_id',
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core_app.team'),
            preserve_default=False,
        ),
    ]
