# Generated by Django 5.0.6 on 2025-11-08 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_remove_teammember_team_id_teammember_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamachievement',
            name='players',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamAchievement',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
