# Generated by Django 5.0.6 on 2025-11-09 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-year', 'sport', 'title'], 'verbose_name_plural': 'User Achievements'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='achievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='achievement',
            table='user_achievements',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
    ]
