# Generated by Django 5.0.6 on 2025-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_metadata'),
        ('profile_app', '0002_alter_achievement_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_id',
            field=models.CharField(blank=True, help_text='Avatar identifier selected by user', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_sports',
            field=models.ManyToManyField(blank=True, help_text='Sports user is interested in (frontend will store IDs)', related_name='interested_profiles', to='bookings.sport'),
        ),
    ]
