# Generated by Django 5.0.6 on 2025-10-30 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ground',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=100, unique=True)),
                ('min_player', models.IntegerField()),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('booked', models.BooleanField(default=False)),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ground', models.ForeignKey(db_column='Ground_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='slots', to='users.ground')),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.AddField(
            model_name='ground',
            name='sport',
            field=models.ForeignKey(db_column='Sport_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='grounds', to='users.sport'),
        ),
        migrations.CreateModel(
            name='SportNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.ForeignKey(db_column='Sports_ID', on_delete=django.db.models.deletion.CASCADE, to='users.sport')),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'unique_together': {('user', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('slot', models.ForeignKey(db_column='Slot_ID', on_delete=django.db.models.deletion.CASCADE, related_name='times', to='users.slot')),
            ],
            options={
                'db_table': 'time_table',
                'unique_together': {('slot', 'time')},
            },
        ),
    ]
