# Generated by Django 5.0.6 on 2025-11-09 14:30

from django.db import migrations
from django.db.models import Count
from django.db.models.functions import Lower


def lowercase_existing_data(apps, schema_editor):
    """Convert existing email and sort_key fields to lowercase and remove duplicates."""
    User = apps.get_model('users', 'User')
    
    # Step 1: Find and remove duplicate emails (case-insensitive)
    # Keep the oldest user (lowest ID) and delete newer duplicates
    duplicates = User.objects.annotate(
        lower_email=Lower('email')
    ).values('lower_email').annotate(
        count=Count('id')
    ).filter(count__gt=1)
    
    for dup in duplicates:
        users = User.objects.filter(email__iexact=dup['lower_email']).order_by('id')
        # Keep the first (oldest) user, delete the rest
        users_to_delete = list(users)[1:]  # All except the first
        for user in users_to_delete:
            print(f"Removing duplicate user: ID={user.id}, Email={user.email}")
            user.delete()
    
    # Step 2: Update remaining users to have lowercase email and sort_key
    users = User.objects.all()
    for user in users:
        updated = False
        if user.email and user.email != user.email.lower():
            user.email = user.email.lower()
            updated = True
        if user.sort_key and user.sort_key != user.sort_key.lower():
            user.sort_key = user.sort_key.lower()
            updated = True
        if updated:
            user.save(update_fields=['email', 'sort_key'])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_unique_user_sort_key_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RunPython(lowercase_existing_data, reverse_code=migrations.RunPython.noop),
    ]

