# Generated by Django 5.0.6 on 2025-10-31 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ground_sport_slot_ground_sport_sportnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('r_mail', models.CharField(max_length=100)),
                ('sort_key', models.CharField(max_length=20)),
                ('user_or_not', models.BooleanField(default=False, verbose_name='Is Registered User')),
                ('ground', models.ForeignKey(db_column='Ground_ID', on_delete=django.db.models.deletion.RESTRICT, to='users.ground')),
                ('slot', models.ForeignKey(db_column='Slot_ID', on_delete=django.db.models.deletion.RESTRICT, to='users.slot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booked Detail',
                'verbose_name_plural': 'Booked Details',
                'db_table': 'booked_details',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Unique Booking ID')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Rejected', 'Rejected'), ('Waitlist Processing', 'Waitlist Processing')], default='Waitlist Processing', max_length=50)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'booking',
            },
        ),
    ]
