# Generated by Django 5.0.6 on 2025-11-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_unique_team_name_teammember_unique_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='achievements',
            field=models.CharField(blank=True, help_text='Team achievements (optional)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='teamachievement',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_records', to='teams.team'),
        ),
    ]
