# Generated by Django 5.0.6 on 2025-11-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_achievements_delete_teamachievement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='team_achievements',
        ),
    ]
