# Generated by Django 5.0.6 on 2025-11-08 21:45

from django.db import migrations, models


def populate_sort_key(apps, schema_editor):
    """Populate sort_key from existing email_id values"""
    TeamMember = apps.get_model('teams', 'TeamMember')
    for member in TeamMember.objects.all():
        email = member.email_id or ''
        member.sort_key = email[:7] if len(email) >= 7 else email
        member.save(update_fields=['sort_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_invitation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='sort_key',
            field=models.CharField(db_index=True, default='', help_text='First 7 chars of email for optimized lookup', max_length=20),
        ),
        migrations.RunPython(populate_sort_key, reverse_code=migrations.RunPython.noop),
    ]
