# Generated by Django 5.0.6 on 2025-11-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_teammember_sort_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='match_details',
            field=models.JSONField(blank=True, help_text='For MATCH_INVITE type: stores sender_team_id, sender_captain_email, message, preferred_date, ground_id', null=True),
        ),
    ]
