# Generated by Django 5.0.6 on 2025-11-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_invitation_match_details'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitation',
            table='invitations',
        ),
    ]
