# Generated by Django 5.0.6 on 2025-10-31 18:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def add_booking_id_column(apps, schema_editor):
    """Add Booking_ID serial column using raw SQL."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "Booking" ADD COLUMN "Booking_ID" SERIAL UNIQUE;'
        )


def remove_booking_id_column(apps, schema_editor):
    """Remove Booking_ID column on migration rollback."""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'ALTER TABLE "Booking" DROP COLUMN IF EXISTS "Booking_ID";'
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('unique_id', models.CharField(db_column='Unique_ID', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('ground_id', models.IntegerField(db_column='Ground_ID')),
                ('slot_id', models.IntegerField(db_column='Slot_ID')),
                ('date', models.DateField(db_column='Date')),
                ('metadata', models.JSONField(blank=True, db_column='Metadata', default=dict)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Rejected', 'Rejected'), ('Waitlist Processing', 'Waitlist Processing')], db_column='Status', default='Waitlist Processing', max_length=30)),
                ('created_at', models.DateTimeField(db_column='Created_At', default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Booking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='Booking_User_ID_7f554f_idx'), models.Index(fields=['ground_id', 'date', 'slot_id'], name='Booking_Ground__41b8c8_idx'), models.Index(fields=['status'], name='Booking_Status_f20062_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Done')), fields=('ground_id', 'slot_id', 'date'), name='unique_active_booking_per_slot'),
        ),
        migrations.RunPython(add_booking_id_column, remove_booking_id_column),
    ]
