# Generated by Django 5.0.6 on 2025-11-04 23:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('ground_id', models.AutoField(db_column='Ground_ID', primary_key=True, serialize=False)),
                ('ground_name', models.CharField(db_column='Ground_Name', max_length=100)),
            ],
            options={
                'verbose_name': 'Ground',
                'verbose_name_plural': 'Grounds',
                'db_table': 'Ground',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sport_id', models.AutoField(db_column='Sport_ID', primary_key=True, serialize=False)),
                ('sport_name', models.CharField(db_column='Sport_Name', max_length=100)),
                ('min_player', models.IntegerField(db_column='Min_Player')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'db_table': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(db_column='Booking_ID', db_index=True, default='', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('metadata', models.JSONField(blank=True, db_column='Metadata', default=dict)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Rejected', 'Rejected'), ('Waitlist Processing', 'Waitlist Processing')], db_column='Status', default='Waitlist Processing', max_length=30)),
                ('created_at', models.DateTimeField(db_column='Created_At', default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='User_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'Booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booked_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_email', models.CharField(db_column='player_email', max_length=100)),
                ('sort_key', models.CharField(db_column='Sort_Key', max_length=20)),
                ('is_user', models.BooleanField(db_column='IsUser', default=False)),
                ('date', models.DateField(db_column='Date')),
                ('slot_id', models.IntegerField(db_column='Slot_ID')),
                ('booking', models.ForeignKey(db_column='Booking_ID', on_delete=django.db.models.deletion.CASCADE, related_name='booked_details', to='bookings.booking')),
                ('ground', models.ForeignKey(db_column='Ground_ID', on_delete=django.db.models.deletion.CASCADE, related_name='booked_details', to='bookings.ground')),
            ],
            options={
                'verbose_name': 'Booked Detail',
                'verbose_name_plural': 'Booked Details',
                'db_table': 'Booked_Details',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(db_column='Slot_ID')),
                ('date', models.DateField(db_column='Date')),
                ('booked', models.BooleanField(db_column='Booked', default=False)),
                ('ground', models.ForeignKey(db_column='Ground_ID', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.ground')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
                'db_table': 'Slot',
            },
        ),
        migrations.AddField(
            model_name='ground',
            name='sport',
            field=models.ForeignKey(db_column='Sport_ID', on_delete=django.db.models.deletion.RESTRICT, related_name='grounds', to='bookings.sport'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'date'], name='Booking_User_ID_7f554f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='Booking_Status_f20062_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('ground', 'date', 'slot_id')},
        ),
    ]
