# Generated by Django 5.0.6 on 2025-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_metadata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='slot',
            index=models.Index(fields=['ground', 'date', 'booked'], name='idx_slot_booked_lookup'),
        ),
    ]
