# Generated by Django 5.0.6 on 2025-11-26 19:03

from django.db import migrations


def populate_sports(apps, schema_editor):
    """
    Populate the Sport table with standard sports and their minimum player requirements.
    """
    Sport = apps.get_model('bookings', 'Sport')
    
    sports_data = [
        (1, 'Football', 11),        # 11 players per team (standard football/soccer)
        (2, 'Basketball', 5),       # 5 players per team
        (3, 'Cricket', 11),         # 11 players per team
        (4, 'Tennis', 2),           # 2 players minimum (singles), can be 4 (doubles)
        (5, 'Badminton', 2),        # 2 players minimum (singles), can be 4 (doubles)
        (6, 'Volleyball', 6),       # 6 players per team
        (7, 'Hockey', 11),          # 11 players per team (field hockey)
        (8, 'Table Tennis', 2),     # 2 players minimum (singles), can be 4 (doubles)
    ]
    
    for sport_id, sport_name, min_player in sports_data:
        Sport.objects.update_or_create(
            sport_id=sport_id,
            defaults={
                'sport_name': sport_name,
                'min_player': min_player,
            }
        )


def reverse_populate_sports(apps, schema_editor):
    """
    Reverse migration: Remove the sports that were added.
    """
    Sport = apps.get_model('bookings', 'Sport')
    sport_ids = [1, 2, 3, 4, 5, 6, 7, 8]
    Sport.objects.filter(sport_id__in=sport_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_slot_idx_slot_booked_lookup'),
    ]

    operations = [
        migrations.RunPython(populate_sports, reverse_populate_sports),
    ]
