# Generated by Django 5.0.6 on 2025-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_ground'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booked_details',
            index=models.Index(fields=['ground', 'date', 'is_user'], name='idx_member_lock'),
        ),
        migrations.AddIndex(
            model_name='booked_details',
            index=models.Index(fields=['player_email', 'is_user'], name='idx_player_lookup'),
        ),
    ]
