# Generated by Django 5.0.6 on 2025-11-26 19:13

from django.db import migrations


def populate_grounds(apps, schema_editor):
    """
    Populate the Ground table with grounds mapped to their respective sports.
    
    Sport IDs:
    1 = Football, 2 = Basketball, 3 = Cricket, 4 = Tennis, 
    5 = Badminton, 6 = Volleyball, 7 = Hockey, 8 = Table Tennis
    """
    Ground = apps.get_model('bookings', 'Ground')
    
    # (ground_id, ground_name, sport_id)
    grounds_data = [
        (1, "Football Ground 1", 1),         # Football
        (2, "Cricket Ground 1", 3),          # Cricket
        (3, "Cricket Ground 2", 3),          # Cricket
        (4, "Hockey Field 1", 7),            # Hockey
        (5, "Basketball Ground 1", 2),       # Basketball
        (6, "Basketball Ground 2", 2),       # Basketball
        (7, "Badminton Court 1", 5),         # Badminton
        (8, "Badminton Court 2", 5),         # Badminton
        (9, "Badminton Court 3", 5),         # Badminton
        (10, "Badminton Court 4", 5),        # Badminton
        (11, "Tennis Court 1", 4),           # Tennis
        (12, "Tennis Court 2", 4),           # Tennis
        (13, "Table Tennis Hall 1", 8),      # Table Tennis
        (14, "Table Tennis Hall 2", 8),      # Table Tennis
        (15, "Table Tennis Hall 3", 8),      # Table Tennis
        (16, "Table Tennis Hall 4", 8),      # Table Tennis
        (17, "Volleyball Court 1", 6),       # Volleyball
    ]
    
    for ground_id, ground_name, sport_id in grounds_data:
        Ground.objects.update_or_create(
            ground_id=ground_id,
            defaults={
                'ground_name': ground_name,
                'sport_id': sport_id,
            }
        )


def reverse_populate_grounds(apps, schema_editor):
    """
    Reverse migration: Remove the grounds that were added.
    """
    Ground = apps.get_model('bookings', 'Ground')
    ground_ids = list(range(1, 18))  # IDs 1-17
    Ground.objects.filter(ground_id__in=ground_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_populate_sports_data'),
    ]

    operations = [
        migrations.RunPython(populate_grounds, reverse_populate_grounds),
    ]
