# Generated by Django 5.0.6 on 2025-11-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the user requesting password reset', max_length=254, verbose_name='Email Address')),
                ('otp', models.CharField(help_text='6-digit OTP code for verification', max_length=6, verbose_name='OTP Code')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the OTP has been successfully verified', verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request was created', verbose_name='Created At')),
                ('expires_at', models.DateTimeField(help_text='Timestamp when the OTP expires (5 minutes from creation)', verbose_name='Expires At')),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', '-created_at'], name='forgot_pass_email_4df8d7_idx'), models.Index(fields=['otp', 'is_verified'], name='forgot_pass_otp_7996f9_idx')],
            },
        ),
    ]
