# Generated by Django 5.0.6 on 2025-11-26 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordResetRequest',
            new_name='ForgotPassword',
        ),
        migrations.RenameIndex(
            model_name='forgotpassword',
            new_name='forgot_pass_email_861f6c_idx',
            old_name='forgot_pass_email_4df8d7_idx',
        ),
        migrations.RenameIndex(
            model_name='forgotpassword',
            new_name='forgot_pass_otp_ac348c_idx',
            old_name='forgot_pass_otp_7996f9_idx',
        ),
    ]
