# Generated by Django 5.0.6 on 2025-11-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgot_password', '0002_rename_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
